services:
  mysql:
    image: mysql:8.0
    container_name: ibanking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ibanking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: ibanking-backend
    ports:
      - "${PORT}:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      OTP_EXPIRE_MINUTES: ${OTP_EXPIRE_MINUTES}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ibanking-network
    volumes:
      - ./backend:/app
      - ./frontend:/app/public
      - /app/node_modules

networks:
  ibanking-network:
    driver: bridge

volumes:
  mysql_data:
